version: '3.7'

services: 

  zookeeper:
    image: zookeeper:3.5.6
    restart: always
    container_name: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    volumes: 
      - ./zookeeper/data:/data

  kafka:
    image: confluentinc/cp-kafka:5.3.2-1
    container_name: kafka
    environment: 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports: 
      - 9092:9092
    volumes: 
      - ./kafka/data:/var/lib/kafka/data
    depends_on: 
      - zookeeper
    links: 
      - zookeeper
